In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

In [26]:
X = np.random.multinomial(n=1, pvals = [4/6,1/6,1/6], size=1000)

In [27]:
X.shape

(1000, 3)

In [28]:
X.sum(axis=0)

array([678, 164, 158])

In [29]:
def fit(X, alpha):
    # X: numpy array N x K
    # alpha: K dim vector
    hat_alpha = X.sum(axis=0) + alpha
    return hat_alpha

In [30]:
hat_alpha = fit(X, [1/3,1/3,1/3])

In [31]:
hat_alpha

array([ 678.33333333,  164.33333333,  158.33333333])

In [32]:
def predict(hat_alpha):
    pvals = hat_alpha / hat_alpha.sum()
    return np.random.multinomial(n=1, pvals=pvals, size=100)

In [33]:
predict(hat_alpha).sum(axis=0)

array([64, 22, 14])